spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: local
  devtools: # 개발 도구 설정
    livereload: # LiveReload 설정
      enabled: true # LiveReload 활성화 여부
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행
