# 공통 설정
spring:
  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
# 로컬 환경 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/gesipan
    username: developer
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace


---
# 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 운영 환경에서는 스키마를 수정하지 않음
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  logging:
    level:
      root: ERROR

server:
  servlet:
    session:
      tracking-modes: cookie  # 세션 추적 방식을 쿠키로만 설정
      timeout: 300

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
